### ISSUE TITLE
 cannot import name 'force_unicode'

### ISSUE THREAD

**Issue by hannibal-zc** [thewub/SlickWiki#1]
Hi there, I'm using python 3.5 and django 1.11. 
After installing, i ran into " cannot import name 'force_unicode'" error when running `python manage.py runserver`. The problem was  fixed with change the `from django.utils.encoding import unicode`  to `from django.utils.encoding import force_text`. 
Thank you for you project. It helps a lot for a beginner.

**Comment by thewub** [comment]
Thanks, should be fixed now. To be honest I'm surprised anyone else even looked at this project, glad to hear it's been helpful!
